# 0x05. Python - Exceptions
## :open_book: At the end of this project, you are expected to be able to explain to anyone, without the help of Google:
 * Why Python programming is awesome
 * What’s the difference between errors and exceptions
 * What are exceptions and how to use them
 * When do we need to use exceptions
 * How to correctly handle an exception
 * What’s the purpose of catching exceptions
 * How to raise a builtin exception
 * When do we need to implement a clean-up action after an exception
## Task
### 0. Safe list printing
Write a function that prints `x` elements of a list.
 * Prototype: `def safe_print_list(my_list=[], x=0):`
### 1. Safe printing of an integers list
Write a function that prints an integer with `"{:d}".format().`
 * Prototype: `def safe_print_integer(value):`
### 2. Print and count integers
Write a function that prints the first `x` elements of a list and only integers.
 * Prototype: `def safe_print_list_integers(my_list=[], x=0):`
### 3. Integers division with debug
Write a function that divides 2 integers and prints the result.
 * Prototype: `def safe_print_division(a, b):`
### 4. Divide a list
Write a function that divides element by element 2 lists.
 * Prototype: `def list_division(my_list_1, my_list_2, list_length):`
### 5. Raise exception
Write a function that raises a type exception.
 * Prototype: `def raise_exception():`
### 6. Raise a message
Write a function that raises a name exception with a message.
 * Prototype: `def raise_exception_msg(message=""):`

